export enum AuditAction {
  ISSUE_INVOICE_QUEUED = 'ISSUE_INVOICE_QUEUED',
  ISSUE_INVOICE_SUCCESS = 'ISSUE_INVOICE_SUCCESS',
  ISSUE_INVOICE_FAILED = 'ISSUE_INVOICE_FAILED',

  MARK_TRANSACTION_PAID = 'MARK_TRANSACTION_PAID',

  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  CREATE_USER = 'CREATE_USER',
}
